#It is also possible to just append Agsyn_Subj to a ton of verbs

DELIMITERS = "." ;

SECTION

ADD  (Agcase_Erg Agsyn_Subj Thcase_Abs Thsyn_Obj) TARGET ("lor");
    ## Mikelek saria lortu du.
    ## Mikel lea vuoitán balkašumi.

ADD  (Caucase_Erg Caucase_Soc Causyn_Subj Expcase_Abs Expsyn_Obj Expsem_Hum) TARGET ("haserre");
    ## Zergatik haserretzen zara nirekin?
    ## Manin don suhtat mu ala/munnje?
    
#ADD  (V) TARGET ("utz");
    ## Utziko al didazu bat?
    ## Attátgo munnje ovtta?
    
ADD  (Agcase_Erg Agsyn_Subj Agsem_Ani) TARGET ("abes");    
    ## Nik abesten dut.
    ## Mun lávllan.

ADD  (Agcase_Erg Agsyn_Subj Agsem_Ani Tocase_Abs Tosyn_Obj Tosem_Ina) TARGET ("abes");    
    ## Nik abesti bat abesten dut.
    ## Mun lávllan lávlaga.

ADD  (Thcase_Abs Thsyn_Subj Locase_Ine Losyn_Advl) TARGET ("ager"); 
    ## Giltza poltsikoan agertu da.
    ## Čoavdda lea ihtán burssas.

ADD  (Thcase_Elasub Thsyn_Subj Locase_Ine Losyn_Advl) TARGET ("ager"); 
    ## Enpresan kargurik ez duela agertu da epaiketan.
    ## Dikkis bođii ovdan ahte sus ii leat miige virgi fitnodagas.

ADD  (Thcase_Abs Thsyn_Subj Sopacase_Abl Sopasyn_Advl Decase_Ala Desyn_Advl) TARGET ("ager"); 
    ## Mikel sukalde aldetik agertu zen egongelara.
    ## Mikel bođii stohpui gievkana bokte.

ADD  (Thcase_Abs Thsyn_Subj Thsem_Hum Prcase_Abs Prsyn_Advl) TARGET ("ager"); 
    ## Mikel urduri agertu zen.
    ## Mikel orui balus.

ADD  (Agcase_Erg Agsyn_Subj Tocase_Abs Tosyn_Obj) TARGET ("ager");     
    ## Mikelek presa gutxi agertzen du.
    ## Mikel orui unnan hoahppus.

ADD  (Agcase_Erg Agsyn_Subj Tocase_Elasub Tosyn_Obj) TARGET ("ager");   
    ## Maite duela agertu dio Mikelek.
    ## Mikel eröffnete ihr seine Liebe.
    
ADD  (Thcase_Abs Thsyn_Subj Sopacase_Abl Sopasyn_Advl Decase_Ala Desyn_Advl) TARGET ("etorr");
ADD  (Thcase_Abs Thsyn_Subj Thsem_Abs Locase_Abl Losyn_Advl Losem_Ina) TARGET ("etorr");
    ## Erabaki horretatik etorri da zure haserrea. 
    ## Tu enfado viene de esa decisión. 
ADD  (Thcase_Abs Thsyn_Subj Thsem_Abs Locase_Dat Losyn_Advl Losem_Ani) TARGET ("etorr");
    ## Mikeli hitza etorri zitzaion bapatean. 
    ## De pronto a Mikel le vino la palabra. 
ADD  (Thcase_Abs Thsyn_Subj Thsem_Ina Locase_Ine Losyn_Advl Losem_Ina) TARGET ("etorr");
    ## Liburu horretan dator jakin nahi duzun guztia
    ## Todo lo que quieres saber viene en ese libro. 
ADD  (Tocase_Abs Tosyn_Subj Locase_Abs Atsyn_Pred) TARGET ("etorr");
    ## Mikel mutiko bihurria zetorren. 
    ## Mikel venía un niño travieso. 

    ## Boađes dal deikke áhku lusa.
    ## Go bohten internáhtii, de cissagohten buvssaide, dan in lean dahkan ovdal.
    ## Ii dáppe lean seammalágan ortnet go duoddaris, gos bohccot bohte ja manne mo dáhtto.
    ## Dalle buohtá ovtta bieivvi, lie viimma mannamin ruoktot.
    ## Preassas lea erenoamaš ovddasvástádus das ahte iešguđet lágan oaivilat bohtet ovdan.

ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum Thcase_Abs Thsyn_Obj) TARGET ("entzun");
    ## Mikelek abestia entzun du.
ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum) TARGET ("entzun");
    ## Mikelek entzuten du.
ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum Thcase_Elasub Thsyn_Obj) TARGET ("entzun");
    ## Mikelek entzun du bihar euria egingo duela.


ADD  (Thcase_Abs Thsyn_Subj Thsem_Ani) TARGET ("hil");
    ## Miren hil da.
    
ADD  (Thcase_Abs Thsyn_Subj Pacase_Abs Pasyn_Obj Pasem_Ani) TARGET ("hil");
    ## Mikelek Miren hil du.

ADD  (Thcase_Abs Thsyn_Subj Sopacase_Abl Sopasyn_Advl Decase_Ala Desyn_Advl) TARGET ("joan");
    ## Mikel eskolatik etxera joan da.

ADD  (Thcase_Abs Thsyn_Subj Thsem_Ina) TARGET ("amai");
    ## Antzerkia amaitu da.
    
ADD  (Agcase_Erg Agsyn_Subj Thcase_Abs Thsyn_Obj Thsem_Ina) TARGET ("amai");
    ## Mikelek pastela amaitu du.
    
ADD  (Agcase_Erg Agsyn_Subj Thcase_Soc Thsyn_Advl) TARGET ("amai");
    ## Mikelek arazoarekin amaitu du.

ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum) TARGET ("ikus");
    ## Mikelek Miren ikusi du.
    
ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum Thcase_Abs Thsyn_Obj) TARGET ("ikus");
    ## Mikelek ikusten du.
    
ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum Thcase_Abs Thsyn_Elasub) TARGET ("ikus");
    ## Mikelek ikusi du partida hasi dela.

#ADD   TARGET ("eman");
    ## Mikelek muxua eman dio Mireni.
    ## Mikelek egunak eman ditu lanean.

ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum Becase_Abs Besyn_Obj Besem_Hum Locase_Ala Losyn_Advl) TARGET ("dei");
    ## Haiek jendea manifestazioara deitu dute.
ADD  (Agcase_Erg Agsyn_Subj Agsem_Hum Becase_Abs Besyn_Obj Besem_Hum Locase_Ala Losyn_Advl) TARGET ("dei");
    ## Haiek manifestazioa deitu dute.
    ## Nik etxera deitu dut.
    ## Nik lagunari telefonoz deitu diot.
    ## Nik hoteletik etxera deitu dut.
    ## Haiek tonto deitu dute Mikel.
    ## Haiek Mikeli tonto deitu diote.


ADD  (Agcase_Erg Agsyn_Subj Tocase_Elasub Tosyn_Obj Recase_Soc Resyn_Advl Resem_Hum) TARGET ("mintz");
    ## Ni zurekin mintzatu naiz atzoko partidari buruz.
    ## Mun lean hállan duinna ievttá čiekčamiid birra.

ADD  (Socase_Abs Sosyn_Subj Sosem_Hum Tocase_Ins Tosyn_Advl Recase_Dat Resyn_Iobj Resem_Hum) TARGET ("mintz");    
    ## Ni zuri mintzatu natzaizu atzoko partidari buruz.
    ## Mun lean hállan duinna ievttá čiekčamiid birra.
    
ADD  (Thcase_Abs Thsyn_Subj Sopacase_Abl Sopasyn_Advl Locase_Ala Losyn_Advl) TARGET ("sar"); #bidjat, mannat
    ## Mikel kaletik tabernara sartu da.
    
ADD  (Thcase_Abs Thsyn_Subj Locase_Ine Losyn_Advl) TARGET ("sar");
    ## Mikel tabernan sartu da.
    
ADD  (Agcase_Erg Agsyn_Subj Thcase_Abs Thsyn_Obj Sopacase_Abl Sopasyn_Advl Locase_Ala Losyn_Advl) TARGET ("sar");
    ## Mikelek paperak poltsatik kaxoira sartu ditu.
    
ADD  (Agcase_Erg Agsyn_Subj Thcase_Abs Thsyn_Obj Locase_Ine Losyn_Advl) TARGET ("sar");
    ## Mikelek paperak kaxoian sartu ditu.



ADD  (Agcase_Erg Agsyn_Subj  Agsem_Hum Thcase_Ins Thsyn_Advl) TARGET ("ahaz");
    ## Mikel Mirenez ahaztu da.
    ## Mikel lea vajálduhttán Mirena.

ADD  (Agcase_Dat Agsyn_Iobj  Agsem_Hum Thcase_Abs Thsyn_Subj) TARGET ("ahaz");    # This is good to show that the agentcase can differ dative in euskara and nominative in Sámi
    ## Mikeli ikasitakoa ahaztu zaio.
    ## Mikel lea vajálduhttán dan maid lea oahppán.
    
ADD  (Agcase_Erg Agsyn_Subj  Agsem_Hum Thcase_Abs Thsyn_Obj) TARGET ("ahaz"); 
       ## Mikelek ikasitakoa ahaztu du.
       ## Mikel lea vajálduhttán dan maid lea oahppán.

ADD  (Agcase_Erg Agsyn_Subj  Agsem_Hum Thcase_Elasub Thsyn_Obj) TARGET ("ahaz");     
    ## Mikelek lanera joan behar zuela ahaztu du.
    ## Mikel ha olvidado que tenía que ir a trabajar.


# use valency to find the correct case in the other language
# use valency to find the correct lexical equivalent (agertu - orrut/boahtit/ihtet)

