DELIMITERS = "." ;

SECTION

ADD (Agcase_Nom Agsyn_Subj Thcase_Acc Thsyn_Obj) TARGET ("vuoitit");
ADD (Agcase_Nom Agsyn_Subj Thcase_Acc Thsyn_Obj) TARGET ("oažžut"); #hartu
# The ambiguity here is more dependend on lexical things
    ## Mikelek saria lortu du.
    ## Mikel lea vuoitán balkašumi.

ADD (Caucase_Nom Causyn_Subj Causem_Hum Expcase_Ill Expcase_ala Expsyn_Advl Expsem_Hum) TARGET ("suhttat");
    ## Zergatik haserretzen zara nirekin?
    ## Manin don suhtat mu ala/munnje?
    
ADD (V) TARGET ("addit");
    ## Utziko al didazu bat?
    ## Attátgo munnje ovtta?
    
ADD (Agcase_Nom Agsyn_Subj Agsem_Ani) TARGET ("lávlut");    
    ## Nik abesten dut.
    ## Mun lávllan.

SUBSTITUTE (Agcase_Nom Agsyn_Subj Agsem_Ani Tocase_Acc Tosyn_Obj Tosem_Ina) TARGET TARGET ("lávlut");    
    ## Nik abesti bat abesten dut.
    ## Mun lávllan lávlaga.

ADD (Thcase_Nom Thsyn_Subj Locase_Loc Losyn_Advl) TARGET ("ihttit"); 
    ## Giltza poltsikoan agertu da.
    ## Čoavdda lea ihtán burssas.

ADD (Thcase_Elasub Thsyn_Subj Locase_Loc Losyn_Advl) TARGET ("boahtit ovdan"); 
    ## Enpresan kargurik ez duela agertu da epaiketan.
    ## Dikkis bođii ovdan ahte sus ii leat miige virgi fitnodagas.

ADD (Thcase_Nom Thsyn_Subj Sopacase_Abl Sopasyn_Advl Decase_bokte Desyn_Advl) TARGET ("boahtit"); 
#This sense is translated as boahtit
    ## Mikel sukalde aldetik agertu zen egongelara.
    ## Mikel bođii stohpui gievkana bokte.

ADD (Thcase_Nom Thsyn_Subj Thsem_Hum Prcase_Nom Prsyn_Advl) TARGET ("ihttit"); 
    ## Mikel urduri agertu zen.
    ## Mikel orui balus.

ADD (Agcase_Nom Agsyn_Subj Tocase_Acc Tosyn_Obj) TARGET ("ihttit");     
    ## Mikelek presa gutxi agertzen du.
    ## Mikel orui unnan hoahppus.

ADD (Agcase_Nom Agsyn_Subj Tocase_Sub Tosyn_Obj) TARGET ("ihttit");   
    ## Maite duela agertu dio Mikelek.
    ## Mikel eröffnete ihr seine Liebe.
    
ADD (Thcase_Abs Thsyn_Subj Sopacase_Abl Sopasyn_Advl Decase_Ala Desyn_Advl) TARGET ("boahtit");
    ## Mikel etxetik eskolara etorri da gaur goizean.
ADD (Thcase_Abs Thsyn_Subj Thsem_Abs Locase_Abl Losyn_Advl Losem_Ina) TARGET ("boahtit");
    ## Erabaki horretatik etorri da zure haserrea. 
    ## Tu enfado viene de esa decisión. 
ADD (Thcase_Abs Thsyn_Subj Thsem_Abs Locase_Dat Losyn_Advl Losem_Ani) TARGET ("boahtit");
    ## Mikeli hitza etorri zitzaion bapatean. 
    ## De pronto a Mikel le vino la palabra. 
ADD (Thcase_Abs Thsyn_Subj Thsem_Ina Locase_Ine Losyn_Advl Losem_Ina) TARGET ("boahtit");
    ## Liburu horretan dator jakin nahi duzun guztia
    ## Todo lo que quieres saber viene en ese libro. 
ADD (Tocase_Abs Tosyn_Subj Locase_Abs Atsyn_Pred) TARGET ("boahtit");
    ## Mikel mutiko bihurria zetorren. 
    ## Mikel venía un niño travieso. 
    
    ## Boađes dal deikke áhku lusa.
    ## Go bohten internáhtii, de cissagohten buvssaide, dan in lean dahkan ovdal.
    ## Ii dáppe lean seammalágan ortnet go duoddaris, gos bohccot bohte ja manne mo dáhtto.
    ## Dalle buohtá ovtta bieivvi, lie viimma mannamin ruoktot.
    ## Preassas lea erenoamaš ovddasvástádus das ahte iešguđet lágan oaivilat bohtet ovdan.
ADD (Agcase_Erg Agsyn_Subj Agsem_Hum Thcase_Abs Thsyn_Obj) TARGET ("entzun");
    ## Mikelek abestia entzun du.
    ## Mikel gullá lávlága.
ADD (Agcase_Erg Agsyn_Subj Agsem_Hum) TARGET ("entzun");
    ## Mikelek entzuten du.
    ## Mikel gullá. #Er det mulig? - guldalit
ADD (Agcase_Erg Agsyn_Subj Agsem_Hum Thcase_Elasub Thsyn_Obj) TARGET ("entzun");
    ## Mikelek entzun du bihar euria egingo duela.
    ## Mikel lea gullán ahte ihttin galgá 
    
ADD (Thcase_Nom Thsyn_Subj Thsem_Ani) TARGET ("hil");
    ## Miren hil da.
    
ADD (Thcase_Nom Thsyn_Subj Pacase_Acc Pasyn_Obj Pasem_Ani) TARGET ("hil");
    ## Mikelek Miren hil du.

ADD (Thcase_Nom Thsyn_Subj Sopacase_Abl Sopasyn_Advl Decase_Ill Desyn_Advl) TARGET ("joan");
    ## Mikel eskolatik etxera joan da.
    ## Mikel vulgii skuvllas ruoktot.
    
    ## Mikel etxera joan da.
    ## Mikel manai ruoktot.

ADD (Thcase_Nom Thsyn_Subj Thsem_Ina) TARGET ("amai");
    ## Antzerkia amaitu da.
    
ADD (Agcase_Nom Agsyn_Subj Thcase_Acc Thsyn_Obj Thsem_Ina) TARGET ("amai");
    ## Mikelek pastela amaitu du.
    
ADD (Agcase_Nom Agsyn_Subj Thcase_Soc Thsyn_Advl) TARGET ("amai");
    ## Mikelek arazoarekin amaitu du.

ADD (Agcase_Nom Agsyn_Subj Agsem_Hum) TARGET ("ikus");
    ## Mikelek Miren ikusi du.
    
ADD (Agcase_Nom Agsyn_Subj Agsem_Hum Thcase_Acc Thsyn_Obj) TARGET ("ikus");
    ## Mikelek ikusten du.
    
ADD (Agcase_Nom Agsyn_Subj Agsem_Hum Thcase_Nom Thsyn_Elasub) TARGET ("ikus");
    ## Mikelek ikusi du partida hasi dela.

ADD (V) TARGET ("eman");
    ## Mikelek muxua eman dio Mireni.
    ## Mikelek egunak eman ditu lanean.

ADD (V) TARGET ("dei");
    ## Haiek jendea manifestazioara deitu dute.
    ## Haiek manifestazioa deitu dute.
    ## Nik etxera deitu dut.
    ## Nik lagunari telefonoz deitu diot.
    ## Nik hoteletik etxera deitu dut.
    ## Haiek tonto deitu dute Mikel.
    ## Haiek Mikeli tonto deitu diote.


ADD (Agcase_Nom Agsyn_Subj Tocase_Sub Tosyn_Obj) TARGET ("mintz");
    ## Ni zurekin mintzatu naiz atzoko partidari buruz.
    ## Mun lean hállan duinna ievttá čiekčamiid birra.

ADD (Socase_Nom Sosyn_Subj Sosem_Hum Tocase_Ins Tosyn_Advl Recase_Dat Resyn_Iobj Resem_Hum) TARGET ("mintz");    
    ## Ni zuri mintzatu natzaizu atzoko partidari buruz.
    ## Mun lean hállan duinna ievttá čiekčamiid birra.
    
ADD (Thcase_Nom Thsyn_Subj Sopacase_Abl Sopasyn_Advl Locase_Ill Losyn_Advl) TARGET ("sar"); #bidjat, mannat
    ## Mikel kaletik tabernara sartu da.
    
ADD (Thcase_Nom Thsyn_Subj Locase_Loc Losyn_Advl) TARGET ("sar");
    ## Mikel tabernan sartu da.
    
ADD (Agcase_Nom Agsyn_Subj Thcase_Acc Thsyn_Obj Sopacase_Abl Sopasyn_Advl Locase_Ill Losyn_Advl) TARGET ("sar");
    ## Mikelek paperak poltsatik kaxoira sartu ditu.
    
ADD (Agcase_Nom Agsyn_Subj Thcase_Acc Thsyn_Obj Locase_Loc Losyn_Advl) TARGET ("sar");
    ## Mikelek paperak kaxoian sartu ditu.



ADD (Agcase_Nom Agsyn_Subj  Agsem_Hum Thcase_Ins Thsyn_Advl) TARGET ("ahaz");
    ## Mikel Mirenez ahaztu da.
    ## Mikel lea vajálduhttán Mirena.

ADD (Agcase_Dat Agsyn_Iobj  Agsem_Hum Thcase_Nom Thsyn_Subj) TARGET ("ahaz");    # This is good to show that the agentcase can differ dative in euskara and nominative in Sámi
    ## Mikeli ikasitakoa ahaztu zaio.
    ## Mikel lea vajálduhttán dan maid lea oahppán.
    
ADD (Agcase_Nom Agsyn_Subj  Agsem_Hum Thcase_Acc Thsyn_Obj) TARGET ("ahaz"); 
       ## Mikelek ikasitakoa ahaztu du.
       ## Mikel lea vajálduhttán dan maid lea oahppán.

ADD (Agcase_Nom Agsyn_Subj  Agsem_Hum Thcase_Sub Thsyn_Obj) TARGET ("ahaz");     
    ## Mikelek lanera joan behar zuela ahaztu du.
    ## Mikel ha olvidado que tenía que ir a trabajar.


# use valency to find the correct case in the other language
# use valency to find the correct lexical equivalent (agertu - orrut/boahtit/ihtet)

